services:
  db:
    image: postgres:18-alpine 
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  backend:
    build: ./apps/backend
    environment:
      DATABASE_URL: postgres://app:app@db:5432/app
    depends_on:
      - db
    ports:
      - "3000:3000"
      

  frontend:
    build: ./apps/frontend/hr_front
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db-data:
